[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "php81", "php81Packages.composer"]
aptPkgs = ["git", "curl", "zip", "unzip", "nodejs", "npm", "php", "php-cli", "php-fpm", "php-mysql", "php-zip", "php-gd", "php-mbstring", "php-curl", "php-xml", "php-bcmath", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"